# Generated by Django 3.2.9 on 2021-11-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineblogApp', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Ratine',
            },
        ),
    ]
